# Generated by Django 4.2 on 2026-02-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='data',
            new_name='date',
        ),
    ]
